---
services:
  app:
    restart: unless-stopped
    ports:
      - "55001:80"
    environment:
      VIRTUAL_HOST: ${HOST_DOMAIN}
    volumes:
      - app-mydb:/app/App_Data
    networks:
      - frontend

volumes:
    app-mydb:

networks:
  frontend:
    external: true
      