---
services:
  app:
    image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION}
    restart: always
    container_name: ${IMAGE_REPO}-app
    environment:
      VIRTUAL_HOST: ${HOST_DOMAIN}
    volumes:
      - app-mydb:/app/App_Data

networks:
  default:
    external: true
    name: frontend

volumes:
  app-mydb:
