name: CI
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-tests:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
