name: Dev Branch Test

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - "dev/**"

jobs:
  run-tests:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
