name: Deploy PR Branch
on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: write
  issues: read

jobs:
  trigger-pr-branch-deploy:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && github.event.issue.state == 'open' && github.event.comment.body == '/deploy'
    steps:
      - name: Get Pull Request Head Ref
        # because Issue will always have the default branch as head ref
        id: get-head-ref
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const response = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number
            });
            console.log(response.data)
            return response.data.head.ref
      - name: Trigger a Branch Deploy
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "deploy.yaml",
              ref: "${{ steps.get-head-ref.outputs.result }}",
              inputs: {
                "environment": `gh-play10-pr-${context.issue.number}`,
                "github-environment": "staging",
                "report-pr": `${context.issue.number}`
              }
            })
            console.log(response)
