name: Test
on:
  workflow_call:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Check for formatting errors
        run: npm run format
      - name: Check for ESlint errors
        run: npm run lint
      - name: Check for type errors
        run: npm run typecheck
      - name: Build the project
        run: npm run build
      #- uses: christopherhx/gitea-upload-artifact@v4
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: .next/
      - name: Run Unit Tests
        run: npm run test
      #- uses: christopherhx/gitea-upload-artifact@v4
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage/
      # upload to codecov
      #- name: Upload coverage to Codecov
      #  uses: codecov/codecov-action@v4
      #  env:
      #    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Store Playwright's Version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
      - name: Cache Playwright Browsers
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install Playwright Browsers
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
      - name: Run E2E Tests
        run: npm run test:e2e
        env:
          FLAGSMITH_KEY: ${{ secrets.FLAGSMITH_KEY }}
      #- uses: christopherhx/gitea-upload-artifact@v4
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e
          path: playwright-report/
      - name: Send to Slack
        if: failure()
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
            "blocks": [
                {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "🛑 *<https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}|${{ github.workflow }} workflow run>* failed."
                }
              }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
